name: Generate and Publish Javadoc

on:
  push:
    branches:
      - master

jobs:
  generate-and-publish-javadoc:
    runs-on: ubuntu-latest
    name: Generate and Publish Javadoc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs/

      - name: Set Permissions for gh-pages branch
        run: |
          git branch gh-pages
          git checkout gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Publish Javadoc to gh-pages"
          git push --force origin gh-pages
